# Nombre de la aplicación
spring.application.name=clinica

# Configuración Dinámica para conectar Render con Supabase
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuración de JPA/Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración específica de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Puerto de la aplicación Spring Boot
server.port=8080

# Logging para ver información
logging.level.org.springframework.boot=INFO
logging.level.org.hibernate.SQL=DEBUG

# Configuración para subida de archivos (Multipart)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.file-size-threshold=2KB

# Configuración para LocalDate
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

# Envío de correos (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=oscarmujica2006@gmail.com
spring.mail.password=tolk pgds gbjt kjvj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.supabase.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=clinicauap2023
spring.jpa.hibernate.ddl-auto=update
